@echo off
echo Starting Google Meet Clone Servers...
echo Starting backend...
start "Signaling Server (Backend)" cmd /k "cd backend && node server.js"
echo Starting frontend...
start "Vite Dev Server (Frontend)" cmd /k "cd frontend && npm run dev"
echo Both servers have been launched in new windows.
